/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegeautomation;

import com.sun.tracing.dtrace.DependencyClass;
import java.awt.Font;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.*;

/**
 *
 * @author PRIYADHARSHINI
 */
public class HourCalculation5 extends javax.swing.JFrame {

    /**
     * Creates new form HourCalculationNew
     */
    public HourCalculation5() {
        initComponents();
        setLocationRelativeTo(null);
        jTable2.getTableHeader().setFont(new Font("Algerian", Font.BOLD, 25));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DM", "TOC", "IP", "OOAD", "CG", "CG LAB", "CT LAB", "IP LAB", "PLACEMENT", "OTHERS" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hour Calculation Sem 5");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select date");

        jDateChooser1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Hour 1", null},
                {"Hour 2", null},
                {"Hour 3", null},
                {"Hour 4", null},
                {"Hour 5", null},
                {"Hour 6", null},
                {"Hour 7", null},
                {"Hour 8", null}
            },
            new String [] {
                "Hour", "HourName"
            }
        ));
        jTable2.setRowHeight(25);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(jComboBox1));
        }

        jButton1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setText("VIEW");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton2)
                .addGap(179, 179, 179))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public static int getDateIfExists(Date date) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/attendance", "root", "");
            PreparedStatement preparedStatement
                    = con.prepareStatement("select date from cse_5");
            ResultSet resultSet = preparedStatement.executeQuery();
            while (resultSet.next()) {
                Date existingDate = resultSet.getDate("date");
                System.out.println(date + " " + existingDate);
                if (date.compareTo(existingDate) == 0) {
                    return 1;
                }
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
        return 0;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int columnCount = jTable2.getRowCount();
        int dm = 0, toc = 0, ip = 0, ooad = 0, cg = 0, cgl = 0, ipl = 0, ctl = 0, others = 0, placement = 0;
        java.util.Date date = jDateChooser1.getDate();
        int flag = 0;
        if (date != null) {
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
            int flagDate = getDateIfExists(sqlDate);
            for (int i = 0; i < columnCount; i++) {
                Object ob = jTable2.getModel().getValueAt(i, 1);
//            "DM", "TOC", "IP", "OOAD", "CG", "CG LAB", "CT LAB", "IP LAB"
                if (!(ob == null || ob.toString().isEmpty())) {
                    String x = ob.toString();

                    switch (x) {
                        case "DM":
                            dm++;
                            break;
                        case "TOC":
                            toc++;
                            break;
                        case "IP":
                            ip++;
                            break;
                        case "OOAD":
                            ooad++;
                            break;
                        case "CG":
                            cg++;
                            break;
                        case "CG LAB":
                            cgl++;
                            break;
                        case "CT LAB":
                            ctl++;
                            break;
                        case "IP LAB":
                            ipl++;
                            break;
                        case "PLACEMENT":
                            placement++;
                            break;
                        case "OTHERS":
                            others++;
                            break;
                    }
                }
            }
            String message = "Are You Sure to want to save the data"+" "+sqlDate+"\n"+"DM : "+dm+"\n"+"TOC : "+toc+"\n"+
                    "IP : "+ip+"\n"+"OOAD : "+ooad+"\n"+"CG : "+cg+"\n"+"CG LAB : "+cgl+"\n CT LAB : "+ctl+"\n IP LAB : "+
                    ipl+"\n PLACEMENT : "+placement+"\n OTHERS : "+others;
            
            int choose = JOptionPane.showConfirmDialog(rootPane, message, "cofirm action", YES_NO_CANCEL_OPTION);
            if(choose == JOptionPane.YES_OPTION){
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/attendance", "root", "");
                if (flagDate == 0) {
                    PreparedStatement preparedStatement = con.prepareStatement("insert into cse_5 (date,dm,ip,ooad,toc,cg,iplab,ctlab,cglab,placement,other) values (?,?,?,?,?,?,?,?,?,?,?)");
                    preparedStatement.setDate(1, sqlDate);
                    preparedStatement.setInt(2, dm);
                    preparedStatement.setInt(3, ip);
                    preparedStatement.setInt(4, ooad);
                    preparedStatement.setInt(5, toc);
                    preparedStatement.setInt(6, cg);
                    preparedStatement.setInt(7, ipl);
                    preparedStatement.setInt(8, ctl);
                    preparedStatement.setInt(9, cgl);
                    preparedStatement.setInt(10, placement);
                    preparedStatement.setInt(11, others);
                    preparedStatement.executeUpdate();
                    flag = 1;
                } else {
                    PreparedStatement preparedStatement = con.prepareStatement("UPDATE cse_5 SET dm = ?, ip = ? ,ooad = ? ,toc = ? ,cg = ? ,iplab =? ,ctlab = ?,cglab = ?,placement =? ,other = ? where date = ? ");
                    preparedStatement.setInt(1, dm);
                    preparedStatement.setInt(2, ip);
                    preparedStatement.setInt(3, ooad);
                    preparedStatement.setInt(4, toc);
                    preparedStatement.setInt(5, cg);
                    preparedStatement.setInt(6, ipl);
                    preparedStatement.setInt(7, ctl);
                    preparedStatement.setInt(8, cgl);
                    preparedStatement.setInt(9, placement);
                    preparedStatement.setInt(10, others);
                    preparedStatement.setDate(11, sqlDate);
                    preparedStatement.executeUpdate();
                    con.close();
                    flag = 1;
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
        }
        
        if(date == null && flag == 0){
            JOptionPane.showMessageDialog(rootPane, "Please select and save values");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        new Welcome().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        new ViewHourCalculator5().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HourCalculation5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HourCalculation5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HourCalculation5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HourCalculation5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HourCalculation5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

}
